server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: env
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  config: classpath:log4j2.yml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
#  mapper-locations: # DatasourceConfig.java에서 설정함
#    - classpath:mapper/**/*.xml