server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: env
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  config: classpath:log4j2.xml
  level:
    web: debug

#  mybatis.configuration: # DatasourceConfig.java에서 설정함